# Generated by Django 3.2.20 on 2023-07-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('BLOCKED', 'BLOCKED'), ('REVIEW', 'REVIEW'), ('COMPLETED', 'COMPLETED')], default='TODO', max_length=20)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('priority', models.IntegerField(blank=True, default=0, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
